service: import-service
frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    SQS_URL: https://sqs.eu-west-1.amazonaws.com/908587837201/catalogItemsQueue

  iamRoleStatements: 
    - Effect: "Allow"
      Action:  "s3:ListBucket"
      Resource: 
      - "arn:aws:s3:::import-cars-bucket"
    - Effect: "Allow"
      Action: 
      - "s3:*"
      Resource: 
      - "arn:aws:s3:::import-cars-bucket/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: 
        - arn:aws:sqs:eu-west-1:908587837201:catalogItemsQueue

functions:
  importProductsFile:
    handler: importObject.createSignedLink
    events:
      - http: 
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer: 
            name: tokenAuthorizer
            arn: arn:aws:lambda:eu-west-1:908587837201:function:authorization-service-dev-basicAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  importFileParser:
    handler: importObject.importFileParser
    events:
      - s3:
          bucket: "import-cars-bucket"
          event: "s3:ObjectCreated:*"
          rules: 
            - prefix: "uploaded/"
          existing: true
