service: import-service
frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

  iamRoleStatements: 
    - Effect: "Allow"
      Action:  "s3:ListBucket"
      Resource: 
      - "arn:aws:s3:::import-cars-bucket"
    - Effect: "Allow"
      Action: 
      - "s3:*"
      Resource: 
      - "arn:aws:s3:::import-cars-bucket/*"

functions:
  importProductsFile:
    handler: importObject.createSignedLink
    events:
      - http: 
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: importObject.importFileParser
    events:
      - s3:
          bucket: "import-cars-bucket"
          event: "s3:ObjectCreated:*"
          rules: 
            - prefix: "uploaded/"
          existing: true
